"""add_achievements_tables

Revision ID: add_achievements_tables
Revises: d617956ef9ba
Create Date: 2026-01-03 06:56:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Table, MetaData, Column, String, Integer, Boolean, DateTime, Date, BigInteger, Float, Text, ForeignKey, PrimaryKeyConstraint, Index

# revision identifiers, used by Alembic.
revision: str = 'add_achievements_tables'
down_revision: Union[str, Sequence[str], None] = 'd617956ef9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define metadata for table objects
metadata = MetaData()

# Define achievements table object for bulk_insert
achievements_table = Table(
    'achievements', metadata,
    Column('id', String(), nullable=False),
    Column('name', String(), nullable=False),
    Column('description', String(), nullable=False),
    Column('type', String(), nullable=False),
    Column('tier', String(), nullable=False),
    Column('requirement_value', Integer(), nullable=False),
    Column('reward_stars', Integer(), nullable=False),
    Column('icon', String(), nullable=False),
    Column('is_active', Boolean(), nullable=False, server_default=sa.text('true')),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=sa.text('now()'))
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tabla de logros
    op.create_table('achievements',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('tier', sa.String(), nullable=False),
        sa.Column('requirement_value', sa.Integer(), nullable=False),
        sa.Column('reward_stars', sa.Integer(), nullable=False),
        sa.Column('icon', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_type'), 'achievements', ['type'], unique=False)
    op.create_index(op.f('ix_achievements_tier'), 'achievements', ['tier'], unique=False)
    
    # Tabla de estadísticas de usuarios
    op.create_table('user_stats',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('total_data_consumed_gb', sa.Float(), nullable=False, server_default=sa.text('0.0')),
        sa.Column('days_active', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('total_referrals', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('total_stars_deposited', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('total_keys_created', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('total_games_won', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('vip_months_purchased', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('last_active_date', sa.Date(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    
    # Tabla de progreso de logros de usuarios
    op.create_table('user_achievements',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('achievement_id', sa.String(), nullable=False),
        sa.Column('current_value', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('is_completed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('reward_claimed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('reward_claimed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_is_completed'), 'user_achievements', ['is_completed'], unique=False)
    
    # Insertar logros predefinidos
    op.bulk_insert(achievements_table, [
        # Consumo de datos
        {'id': 'data_bronze_1', 'name': 'Primeros Pasos', 'description': 'Consume 1 GB de datos', 'type': 'data_consumed', 'tier': 'bronze', 'requirement_value': 1, 'reward_stars': 5, 'icon': '🥉'},
        {'id': 'data_bronze_2', 'name': 'Navegante', 'description': 'Consume 5 GB de datos', 'type': 'data_consumed', 'tier': 'bronze', 'requirement_value': 5, 'reward_stars': 10, 'icon': '🥉'},
        {'id': 'data_silver_1', 'name': 'Explorador', 'description': 'Consume 10 GB de datos', 'type': 'data_consumed', 'tier': 'silver', 'requirement_value': 10, 'reward_stars': 25, 'icon': '🥈'},
        {'id': 'data_silver_2', 'name': 'Viajero Frecuente', 'description': 'Consume 25 GB de datos', 'type': 'data_consumed', 'tier': 'silver', 'requirement_value': 25, 'reward_stars': 50, 'icon': '🥈'},
        {'id': 'data_gold_1', 'name': 'Conquistador', 'description': 'Consume 50 GB de datos', 'type': 'data_consumed', 'tier': 'gold', 'requirement_value': 50, 'reward_stars': 100, 'icon': '🥇'},
        {'id': 'data_gold_2', 'name': 'Maestro de Datos', 'description': 'Consume 100 GB de datos', 'type': 'data_consumed', 'tier': 'gold', 'requirement_value': 100, 'reward_stars': 200, 'icon': '🥇'},
        {'id': 'data_platinum_1', 'name': 'Leyenda Digital', 'description': 'Consume 250 GB de datos', 'type': 'data_consumed', 'tier': 'platinum', 'requirement_value': 250, 'reward_stars': 500, 'icon': '💎'},
        {'id': 'data_diamond_1', 'name': 'Titán de la Red', 'description': 'Consume 500 GB de datos', 'type': 'data_consumed', 'tier': 'diamond', 'requirement_value': 500, 'reward_stars': 1000, 'icon': '💍'},
        
        # Días activos
        {'id': 'days_bronze_1', 'name': 'Novato', 'description': 'Usa el bot por 1 día', 'type': 'days_active', 'tier': 'bronze', 'requirement_value': 1, 'reward_stars': 3, 'icon': '🥉'},
        {'id': 'days_bronze_2', 'name': 'Regular', 'description': 'Usa el bot por 7 días', 'type': 'days_active', 'tier': 'bronze', 'requirement_value': 7, 'reward_stars': 15, 'icon': '🥉'},
        {'id': 'days_silver_1', 'name': 'Dedicado', 'description': 'Usa el bot por 30 días', 'type': 'days_active', 'tier': 'silver', 'requirement_value': 30, 'reward_stars': 50, 'icon': '🥈'},
        {'id': 'days_silver_2', 'name': 'Constante', 'description': 'Usa el bot por 90 días', 'type': 'days_active', 'tier': 'silver', 'requirement_value': 90, 'reward_stars': 100, 'icon': '🥈'},
        {'id': 'days_gold_1', 'name': 'Veterano', 'description': 'Usa el bot por 180 días', 'type': 'days_active', 'tier': 'gold', 'requirement_value': 180, 'reward_stars': 200, 'icon': '🥇'},
        {'id': 'days_gold_2', 'name': 'Experto', 'description': 'Usa el bot por 365 días', 'type': 'days_active', 'tier': 'gold', 'requirement_value': 365, 'reward_stars': 500, 'icon': '🥇'},
        {'id': 'days_platinum_1', 'name': 'Maestro', 'description': 'Usa el bot por 730 días', 'type': 'days_active', 'tier': 'platinum', 'requirement_value': 730, 'reward_stars': 1000, 'icon': '💎'},
        {'id': 'days_diamond_1', 'name': 'Leyenda', 'description': 'Usa el bot por 1000 días', 'type': 'days_active', 'tier': 'diamond', 'requirement_value': 1000, 'reward_stars': 2000, 'icon': '💍'},
        
        # Referidos
        {'id': 'ref_bronze_1', 'name': 'Amigos', 'description': 'Refiere 1 usuario', 'type': 'referrals_count', 'tier': 'bronze', 'requirement_value': 1, 'reward_stars': 10, 'icon': '🥉'},
        {'id': 'ref_bronze_2', 'name': 'Conector', 'description': 'Refiere 3 usuarios', 'type': 'referrals_count', 'tier': 'bronze', 'requirement_value': 3, 'reward_stars': 30, 'icon': '🥉'},
        {'id': 'ref_silver_1', 'name': 'Influencer', 'description': 'Refiere 5 usuarios', 'type': 'referrals_count', 'tier': 'silver', 'requirement_value': 5, 'reward_stars': 75, 'icon': '🥈'},
        {'id': 'ref_silver_2', 'name': 'Líder', 'description': 'Refiere 10 usuarios', 'type': 'referrals_count', 'tier': 'silver', 'requirement_value': 10, 'reward_stars': 150, 'icon': '🥈'},
        {'id': 'ref_gold_1', 'name': 'Mentor', 'description': 'Refiere 25 usuarios', 'type': 'referrals_count', 'tier': 'gold', 'requirement_value': 25, 'reward_stars': 400, 'icon': '🥇'},
        {'id': 'ref_gold_2', 'name': 'Gurú', 'description': 'Refiere 50 usuarios', 'type': 'referrals_count', 'tier': 'gold', 'requirement_value': 50, 'reward_stars': 1000, 'icon': '🥇'},
        {'id': 'ref_platinum_1', 'name': 'Estrella', 'description': 'Refiere 100 usuarios', 'type': 'referrals_count', 'tier': 'platinum', 'requirement_value': 100, 'reward_stars': 2500, 'icon': '💎'},
        {'id': 'ref_diamond_1', 'name': 'Leyenda', 'description': 'Refiere 250 usuarios', 'type': 'referrals_count', 'tier': 'diamond', 'requirement_value': 250, 'reward_stars': 5000, 'icon': '💍'},
        
        # Estrellas depositadas
        {'id': 'stars_bronze_1', 'name': 'Inversor', 'description': 'Deposita 10 estrellas', 'type': 'stars_deposited', 'tier': 'bronze', 'requirement_value': 10, 'reward_stars': 5, 'icon': '🥉'},
        {'id': 'stars_bronze_2', 'name': 'Ahorrista', 'description': 'Deposita 50 estrellas', 'type': 'stars_deposited', 'tier': 'bronze', 'requirement_value': 50, 'reward_stars': 25, 'icon': '🥉'},
        {'id': 'stars_silver_1', 'name': 'Banquero', 'description': 'Deposita 100 estrellas', 'type': 'stars_deposited', 'tier': 'silver', 'requirement_value': 100, 'reward_stars': 60, 'icon': '🥈'},
        {'id': 'stars_silver_2', 'name': 'Financiero', 'description': 'Deposita 250 estrellas', 'type': 'stars_deposited', 'tier': 'silver', 'requirement_value': 250, 'reward_stars': 150, 'icon': '🥈'},
        {'id': 'stars_gold_1', 'name': 'Magnate', 'description': 'Deposita 500 estrellas', 'type': 'stars_deposited', 'tier': 'gold', 'requirement_value': 500, 'reward_stars': 350, 'icon': '🥇'},
        {'id': 'stars_gold_2', 'name': 'Titán', 'description': 'Deposita 1000 estrellas', 'type': 'stars_deposited', 'tier': 'gold', 'requirement_value': 1000, 'reward_stars': 800, 'icon': '🥇'},
        {'id': 'stars_platinum_1', 'name': 'Mogul', 'description': 'Deposita 2500 estrellas', 'type': 'stars_deposited', 'tier': 'platinum', 'requirement_value': 2500, 'reward_stars': 2000, 'icon': '💎'},
        {'id': 'stars_diamond_1', 'name': 'Legendario', 'description': 'Deposita 5000 estrellas', 'type': 'stars_deposited', 'tier': 'diamond', 'requirement_value': 5000, 'reward_stars': 5000, 'icon': '💍'},
        
        # Claves creadas
        {'id': 'keys_bronze_1', 'name': 'Principiante', 'description': 'Crea 1 clave', 'type': 'keys_created', 'tier': 'bronze', 'requirement_value': 1, 'reward_stars': 2, 'icon': '🥉'},
        {'id': 'keys_bronze_2', 'name': 'Práctico', 'description': 'Crea 5 claves', 'type': 'keys_created', 'tier': 'bronze', 'requirement_value': 5, 'reward_stars': 10, 'icon': '🥉'},
        {'id': 'keys_silver_1', 'name': 'Experto en Claves', 'description': 'Crea 10 claves', 'type': 'keys_created', 'tier': 'silver', 'requirement_value': 10, 'reward_stars': 25, 'icon': '🥈'},
        {'id': 'keys_silver_2', 'name': 'Coleccionista', 'description': 'Crea 25 claves', 'type': 'keys_created', 'tier': 'silver', 'requirement_value': 25, 'reward_stars': 60, 'icon': '🥈'},
        {'id': 'keys_gold_1', 'name': 'Maestro de Claves', 'description': 'Crea 50 claves', 'type': 'keys_created', 'tier': 'gold', 'requirement_value': 50, 'reward_stars': 150, 'icon': '🥇'},
        {'id': 'keys_gold_2', 'name': 'Generador', 'description': 'Crea 100 claves', 'type': 'keys_created', 'tier': 'gold', 'requirement_value': 100, 'reward_stars': 300, 'icon': '🥇'},
        {'id': 'keys_platinum_1', 'name': 'Factory', 'description': 'Crea 250 claves', 'type': 'keys_created', 'tier': 'platinum', 'requirement_value': 250, 'reward_stars': 800, 'icon': '💎'},
        {'id': 'keys_diamond_1', 'name': 'Infinity', 'description': 'Crea 500 claves', 'type': 'keys_created', 'tier': 'diamond', 'requirement_value': 500, 'reward_stars': 1500, 'icon': '💍'},
        
        # Juegos ganados
        {'id': 'games_bronze_1', 'name': 'Jugador', 'description': 'Gana 1 juego', 'type': 'games_won', 'tier': 'bronze', 'requirement_value': 1, 'reward_stars': 3, 'icon': '🥉'},
        {'id': 'games_bronze_2', 'name': 'Competidor', 'description': 'Gana 5 juegos', 'type': 'games_won', 'tier': 'bronze', 'requirement_value': 5, 'reward_stars': 15, 'icon': '🥉'},
        {'id': 'games_silver_1', 'name': 'Campeón', 'description': 'Gana 10 juegos', 'type': 'games_won', 'tier': 'silver', 'requirement_value': 10, 'reward_stars': 35, 'icon': '🥈'},
        {'id': 'games_silver_2', 'name': 'Ganador', 'description': 'Gana 25 juegos', 'type': 'games_won', 'tier': 'silver', 'requirement_value': 25, 'reward_stars': 80, 'icon': '🥈'},
        {'id': 'games_gold_1', 'name': 'Maestro', 'description': 'Gana 50 juegos', 'type': 'games_won', 'tier': 'gold', 'requirement_value': 50, 'reward_stars': 180, 'icon': '🥇'},
        {'id': 'games_gold_2', 'name': 'Leyenda', 'description': 'Gana 100 juegos', 'type': 'games_won', 'tier': 'gold', 'requirement_value': 100, 'reward_stars': 400, 'icon': '🥇'},
        {'id': 'games_platinum_1', 'name': 'Inmortal', 'description': 'Gana 250 juegos', 'type': 'games_won', 'tier': 'platinum', 'requirement_value': 250, 'reward_stars': 1000, 'icon': '💎'},
        {'id': 'games_diamond_1', 'name': 'Dios', 'description': 'Gana 500 juegos', 'type': 'games_won', 'tier': 'diamond', 'requirement_value': 500, 'reward_stars': 2000, 'icon': '💍'},
        
        # VIP
        {'id': 'vip_bronze_1', 'name': 'VIP Novato', 'description': 'Compra 1 mes VIP', 'type': 'vip_months', 'tier': 'bronze', 'requirement_value': 1, 'reward_stars': 5, 'icon': '🥉'},
        {'id': 'vip_bronze_2', 'name': 'VIP Regular', 'description': 'Compra 3 meses VIP', 'type': 'vip_months', 'tier': 'bronze', 'requirement_value': 3, 'reward_stars': 20, 'icon': '🥉'},
        {'id': 'vip_silver_1', 'name': 'VIP Dedicado', 'description': 'Compra 6 meses VIP', 'type': 'vip_months', 'tier': 'silver', 'requirement_value': 6, 'reward_stars': 50, 'icon': '🥈'},
        {'id': 'vip_silver_2', 'name': 'VIP Leal', 'description': 'Compra 12 meses VIP', 'type': 'vip_months', 'tier': 'silver', 'requirement_value': 12, 'reward_stars': 100, 'icon': '🥈'},
        {'id': 'vip_gold_1', 'name': 'VIP Elite', 'description': 'Compra 24 meses VIP', 'type': 'vip_months', 'tier': 'gold', 'requirement_value': 24, 'reward_stars': 250, 'icon': '🥇'},
        {'id': 'vip_gold_2', 'name': 'VIP Supremo', 'description': 'Compra 36 meses VIP', 'type': 'vip_months', 'tier': 'gold', 'requirement_value': 36, 'reward_stars': 500, 'icon': '🥇'},
        {'id': 'vip_platinum_1', 'name': 'VIP Leyenda', 'description': 'Compra 60 meses VIP', 'type': 'vip_months', 'tier': 'platinum', 'requirement_value': 60, 'reward_stars': 1000, 'icon': '💎'},
        {'id': 'vip_diamond_1', 'name': 'VIP Eterno', 'description': 'Compra 120 meses VIP', 'type': 'vip_months', 'tier': 'diamond', 'requirement_value': 120, 'reward_stars': 2500, 'icon': '💍'},
    ])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievements')
    op.drop_table('user_stats')
    op.drop_table('achievements')
    # ### end Alembic commands ###
